### ISSUE TITLE
jsfour-idcard

### ISSUE THREAD

**Issue by Venakiel** [Korioz/krz_personalmenu#1]
Salut, voilà j'aurais souhaiter que l'ont puisse montrer le permis de conduire et le permis port d'arme tout comme la carte d'identité, j'ai réussi a avancé un peux mais je suis bloqué, je parvient a voir mon ppa et permis de conduire mais pas à les montrer ?

	if Config.EnableESXIdentity then
		local showID = NativeUI.CreateItem("Montrer sa carte d'identité", "")
		walletmenu.SubMenu:AddItem(showID)

		local checkID = NativeUI.CreateItem("Regarder sa carte d'identité", "")
		walletmenu.SubMenu:AddItem(checkID)
		
		local showDR = NativeUI.CreateItem("Montrer son permis", "")
		walletmenu.SubMenu:AddItem(showDR)

		local checkDR = NativeUI.CreateItem("Regarder son permis", "")
		walletmenu.SubMenu:AddItem(checkDR)
		
		local showPA = NativeUI.CreateItem("Montrer son port d'arme", "")
		walletmenu.SubMenu:AddItem(showPA)

		local checkPA = NativeUI.CreateItem("Regarder son port d'arme", "")
		walletmenu.SubMenu:AddItem(checkPA)

		walletmenu.SubMenu.OnItemSelect = function(sender, item, index)
			if item == showID then
				personalmenu.closestPlayer, personalmenu.closestDistance = ESX.Game.GetClosestPlayer()
											
				if personalmenu.closestDistance ~= -1 and personalmenu.closestDistance <= 3.0 then
					TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(PlayerId()), GetPlayerServerId(personalmenu.closestPlayer))
				else
					ESX.ShowNotification("Aucun citoyen à proximité")
				end
			elseif item == checkID then
				TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(PlayerId()), GetPlayerServerId(PlayerId()))
			elseif item == checkDR then
				TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(PlayerId()), GetPlayerServerId(PlayerId()), 'driver')
			elseif item == checkPA then
				TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(PlayerId()), GetPlayerServerId(PlayerId()), 'weapon')
			end
		end
	end

Merci de ton aide

**Comment by Korioz** [comment]
Une mise a jour arrive d'ici quelques heures je vais d'abord terminer les traductions ✔

**Comment by juliencdn** [comment]
Bonjour, j'aimerai savoir si vous mettrez en ligne la version ou nous pourrions montrer notre carte d'identité, permis...? Je vous remercie d'avance

**Comment by Venakiel** [comment]
> Bonjour, j'aimerai savoir si vous mettrez en ligne la version ou nous pourrions montrer notre carte d'identité, permis...? Je vous remercie d'avance

Salut, c'est disponible, je les sur mon serveur et je les pris ici après la mise a jour :)

**Comment by juliencdn** [comment]
Salut, merci pour ta réponse.
J'ai télécharger la nouvelle version, j'ai mis :
Config.EnableJsfourIDCard = true -- enable if you're using jsfour-idcard
Sur true car j'utilise ce système, mais je ne peut pas regarder, je ne peut que montrer.

**Comment by Venakiel** [comment]
Tu as bien [jsfour-idcard](https://github.com/jonassvensson4/jsfour-idcard) ? Car moi je n'ai aucun soucis a ce niveau

**Comment by Korioz** [comment]
Il faut utiliser jsfour-idcard sur sa derniere version et penser a le start avant le menu perso

**Comment by juliencdn** [comment]
Ok merci, je vais faire comme ça, je n'ai pas penser à vérifier les mises à jours du côté de jsfour-idcard
