### ISSUE TITLE
ESX-legacy money not showing up

### ISSUE THREAD

**Issue by ThePaintsmoker** [Korioz/krz_personalmenu#109]
Hey, since updating to esx legacy the cash doesnt show up. I tried the provided patches in the pull requests but they don't work.

**Comment by bitpredator** [comment]
> Hey, since updating to esx legacy the cash doesnt show up. I tried the provided patches in the pull requests but they don't work.

I just tested legacy esx version 1.7.5 and everything works fine. do you have any other information or errors in the console?
