### ISSUE TITLE
SCRIPT ERROR: @krz_personalmenu/client/main.lua:1153: attempt to index a nil value (global 'ESX')

### ISSUE THREAD

**Issue by itunxRedPanda** [Korioz/krz_personalmenu#114]
![image](https://user-images.githubusercontent.com/47486854/211152732-99c9e61b-54c3-4cde-807e-d0220a4803da.png)
![image](https://user-images.githubusercontent.com/47486854/211152757-f1aaca07-4173-4f6f-ab63-d2267c1b4297.png)
![image](https://user-images.githubusercontent.com/47486854/211153332-0710a4ec-7263-4ba0-8e02-0a25d4040235.png)

I've been trying to solve this problem for a long time, but I just can't do it.

**Comment by Korioz** [comment]
The issue come from your `es_extended` resource, it could be the name of the event which get the ESX object which has been changed or the resource which is started before `es_extended`.
