### ISSUE TITLE
'givemoney' problem, have solved it myself here the change 

### ISSUE THREAD

**Issue by itunxRedPanda** [Korioz/krz_personalmenu#115]
Good day, I don't know if you are still updating the Krz_personalmene but I definitely wanted to let you know that in config.lua the trigger event is 

`TriggerServerEvent('krz_personalmenu:Admin_giveCash', Amount) `

should be changed to 

`TriggerServerEvent('krz_personalmenu:Admin_giveMoney', Amount) `

the same applies to server/main.lua 

with the trigger event [Cash] I could not give myself money

i hope this information was helpful for you and have a nice day

**Comment by Korioz** [comment]
You can give yourself because you are admin.
