### ISSUE TITLE
SCRIPT ERROR: @krz_personalmenu/client/other.lua:82: attempt to index a function value (global 'Player')

### ISSUE THREAD

**Issue by juxky** [Korioz/krz_personalmenu#118]
![image](https://user-images.githubusercontent.com/131326840/233247156-ee5322ba-2a55-45f2-b087-cd416b7ad94b.png)
its load with this Error in live Console

![image](https://user-images.githubusercontent.com/131326840/233247353-251ac684-a68f-4346-b851-a5f4e44ac0f0.png)

**Comment by Dreamxdevil** [comment]
I have the same issue

**Comment by philippbkrr** [comment]
same here, any fix?

**Comment by Dreamxdevil** [comment]
have add the new esx getshared event and have forgot to delete the end) in line 46 I think

**Comment by philippbkrr** [comment]
Could you send me your file


> have add the new esx getshared event and have forgot to delete the end) in line 46 I think

could you send me your file?

**Comment by Dreamxdevil** [comment]
> Could you send me your file
> 
> 
> > have add the new esx getshared event and have forgot to delete the end) in line 46 I think
> 
> could you send me your file?

Add me on discord DreamxDevil#3429

**Comment by Korioz** [comment]
Player cannot be a function in the code so you probably have modified it or downloaded a modified version.
