### ISSUE TITLE
Helloo... 

### ISSUE THREAD

**Issue by BellaStreet** [Korioz/krz_personalmenu#119]
Hello Dear, 
Normally i never had any problems with your Script but since 3 days i simply dont know what to do. 
We had to update our server to the latest Legacything, and since then The Menue kind of was annoyed by everything - I was able to fix most of it ( mostly my own mistakes) but its still not working the way it should and it screams from the top of the lungs : 

[    c-scripting-core] Creating script environments for krz_personalmenu
[script:krz_personalm] ======================================================================
[script:krz_personalm] [Author] : Korioz
[script:krz_personalm] [Version] : 2.1
[script:krz_personalm] [Download] : https://github.com/korioz/krz_personalmenu/releases
[script:krz_personalm] [Issues] : https://github.com/korioz/krz_personalmenu/issues
[script:krz_personalm] ======================================================================
[script:krz_personalm] Error loading script server/main.lua in resource krz_personalmenu: @krz_personalmenu/server/main.lua:5: attempt to index a nil value (global 'ESX')
[script:krz_personalm] stack traceback:
[script:krz_personalm] 	@krz_personalmenu/server/main.lua:5: in main chunk

I really dont know, what to do anymore right now .. ( or im just simply too idiotic for it) but do you have a solution to this? 

Kind regards 
Bella

**Comment by Korioz** [comment]
Idk too, esx is a mess they have multiple versions and each one of them breaks things, try an older version or the latest you can download.
