### ISSUE TITLE
The menu does not open

### ISSUE THREAD

**Issue by FrankenRoleplay** [Korioz/krz_personalmenu#124]
I'm using the latest version of ESX, and the menu won't open I don't have an error or anything else and the menu doesn't show up in my keyboard layouts

**Comment by bitpredator** [comment]
Hi @FrankenRoleplay , I will check your problem today and let you know.

**Comment by bitpredator** [comment]
Hi @FrankenRoleplay , I just tested version 2.2 of krz_personalmenu with ESX version 1.10.2 released on September 21st, and the menu opens correctly.

**Comment by BugBoys100** [comment]
Hi, I would like to reopen this issue to tell you that the menu does not open for me either, I added a print to the client code, the print is displayed in the console but nothing happens, I am in version es_extended 1.10.2 and I have no errors in the console. The different commands (noclip, bring etc) work perfectly, it's just the menu that doesn't open.

```lua
Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)

		if IsControlJustReleased(0, Config.Controls.OpenMenu.keyboard) and not PlayerVars.isDead then

			print("fff")

			if not RageUI.Visible() then
				ESX.TriggerServerCallback('krz_personalmenu:Admin_getUsergroup', function(plyGroup)
					PlayerVars.group = plyGroup
					ESX.TriggerServerCallback('krz_personalmenu:Bill_getBills', function(bills)
						PersonalMenu.BillData = bills
						ESX.PlayerData = ESX.GetPlayerData()
						RageUI.Visible(RMenu.Get('rageui', 'personal'), true)
					end)
				end)
			end
		end

```

**Comment by Korioz** [comment]
Fixed in latest release
