### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by splashpunk** [Korioz/krz_personalmenu#125]
For some things I can press it and it crashes, so to speak, the script crashes. The error is in the picture.
![Screenshot 2023-12-21 151312](https://github.com/Korioz/krz_personalmenu/assets/151228901/48d46b48-dd15-4ce7-8457-d6745ca8a50a)

**Comment by Korioz** [comment]
Download the latest

**Comment by Korioz** [comment]
Thank's for the report, this is fixed in last version.
