### ISSUE TITLE
wallet money slider not working

### ISSUE THREAD

**Issue by MauriceHandwerker** [Korioz/krz_personalmenu#129]
Hi for some reason the money slider doesent work. 
![image](https://github.com/Korioz/krz_personalmenu/assets/66009198/d7256caa-6bce-41ed-9287-f265cdb67f45)

If I try to go trough the options with the arrow keys I hear the sound but the option doesent change. 
It stays with give.

**Comment by Korioz** [comment]
Fixed 416f0ca8c856bf8e3d9ca80ca55c5c347363b9f9
