### ISSUE TITLE
help! its possible?

### ISSUE THREAD

**Issue by SliderKP** [Korioz/krz_personalmenu#13]
its possible to close menu with...
			ESX.UI.Menu.CloseAll()

thanks.

**Comment by Korioz** [comment]
No it's not a ESX Menu it's created with NativeUI Lua Reloaded

**Comment by SliderKP** [comment]
@Korioz okey, and any function similar to close krz_personalmenu?
because i have a bug, if menu not closing in some event, can multiplicate items farming, any way?

Thanks for your answer!

**Comment by Korioz** [comment]
You can create an event that use RageUI.CloseAll function like that below

AddEventHandler('krz_personalmenu:closeMenu', function()
	RageUI.CloseAll()
end)
