### ISSUE TITLE
Diferent torso_1 in male and female

### ISSUE THREAD

**Issue by jafuente** [Korioz/krz_personalmenu#20]
I would need you to check the sex in torso_1, because the skin is different. I tried to do the same check you do with pants but it doesn't work. This is my code.

				if skin.torso_1 ~= skina.torso_1 then
					TriggerEvent('skinchanger:loadClothes', skina, {['torso_1'] = skin.torso_1, ['torso_2'] = skin.torso_2, ['tshirt_1'] = skin.tshirt_1, ['tshirt_2'] = skin.tshirt_2, ['arms'] = skin.arms})
				else
					if skin.sex == 0 then
						TriggerEvent('skinchanger:loadClothes', skina, {['torso_1'] = 15, ['torso_2'] = 0, ['tshirt_1'] = 57, ['tshirt_2'] = 0, ['arms'] = 15})
					else
						TriggerEvent('skinchanger:loadClothes', skina, {['torso_1'] = 15, ['torso_2'] = 0, ['tshirt_1'] = 7, ['tshirt_2'] = 0, ['arms'] = 15})
					end
				end

Where are problem ?

**Comment by Korioz** [comment]
Describe the error cause "it doesn't work" never gonna help anyone.
