### ISSUE TITLE
bring command don't work

### ISSUE THREAD

**Issue by tholeb** [Korioz/krz_personalmenu#23]
bring command actually make a goto command command :/

**Comment by CaliforniaFiveM** [comment]
you need onesync as i told in requirements

**Comment by Korioz** [comment]
Weird are you sure you are using OneSync as said in requirements ?

**Comment by tholeb** [comment]
Hey, yes, i also looked at the code and it calls the bring command if I remember well, and also the cloak and the noclip's cloak only work for few seconds

**Comment by Korioz** [comment]
I think cloak don't work well cause of another resource who set your ped alpha to another like to prevent hackers or something else for the other part that's normal it call the bring event but don't use the same params i will investigate and tell you.

**Comment by tholeb** [comment]
Ok, thanks for the info, do you think easyadmin and/or easyadmin-anticheat is the cause of the issue for the cloak ?

**Comment by Korioz** [comment]
Try to stop resources that you think it's the cause and you will se what resource cause the problem

**Comment by Richards0nd** [comment]
Na verdade isso realmente é algo sem roteiro.
Estou com o mesmo problema ...
Não estou usando nenhum anticheat, e mesmo assim não funciona.

**Comment by Richards0nd** [comment]
In fact, this is really something without a script.
I have the same problem ...
I'm not using any anticheat, and it still doesn't work.

**Comment by Berkeratay** [comment]
Any updates on this?
Seems like both goto and bring the same command which they are doing the same thing.

	```
{
		name = 'goto',
		label = _U('admin_goto_button'),
		groups = {'_dev', 'owner', 'superadmin', 'admin', 'mod'},
		command = function()
			local plyId = KeyboardInput('KORIOZ_BOX_ID', _U('dialogbox_playerid'), '', 8)

			if plyId ~= nil then
				plyId = tonumber(plyId)
				
				if type(plyId) == 'number' then
					TriggerServerEvent('KorioZ-PersonalMenu:Admin_BringS', GetPlayerServerId(PlayerId()), plyId)
				end
			end

			RageUI.CloseAll()
		end
	},
	{
		name = 'bring',
		label = _U('admin_bring_button'),
		groups = {'_dev', 'owner', 'superadmin', 'admin', 'mod'},
		command = function()
			local plyId = KeyboardInput('KORIOZ_BOX_ID', _U('dialogbox_playerid'), '', 8)

			if plyId ~= nil then
				plyId = tonumber(plyId)
				
				if type(plyId) == 'number' then
					TriggerServerEvent('KorioZ-PersonalMenu:Admin_BringC', GetPlayerServerId(PlayerId()), plyId)
				end
			end

			RageUI.CloseAll()
		end
	},
```

**Comment by tjspann** [comment]
I actually fixed this for myself:

```
{
		name = 'goto',
		label = _U('admin_goto_button'),
		groups = {'_dev', 'owner', 'superadmin', 'admin', 'mod'},
		command = function()
			local plyId = KeyboardInput('KORIOZ_BOX_ID', _U('dialogbox_playerid'), '', 8)

			if plyId ~= nil then
				plyId = tonumber(plyId)
				
				if type(plyId) == 'number' then
					TriggerServerEvent('KorioZ-PersonalMenu:Admin_BringS', GetPlayerServerId(PlayerId()), plyId)
				end
			end

			RageUI.CloseAll()
		end
	},
	{
		name = 'bring',
		label = _U('admin_bring_button'),
		groups = {'_dev', 'owner', 'superadmin', 'admin', 'mod'},
		command = function()
			local plyId = KeyboardInput('KORIOZ_BOX_ID', _U('dialogbox_playerid'), '', 8)

			if plyId ~= nil then
				plyId = tonumber(plyId)
				
				if type(plyId) == 'number' then
					TriggerServerEvent('KorioZ-PersonalMenu:Admin_BringS', plyId, GetPlayerServerId(PlayerId()))
				end
			end

			RageUI.CloseAll()
		end
	},
```

It was the same command on both sides. Now it's not. You're welcome.

**Comment by Korioz** [comment]
fixed for a long time.
