### ISSUE TITLE
[NEED INFO] Menu won't open sometimes in cars

### ISSUE THREAD

**Issue by Neo1030** [Korioz/krz_personalmenu#28]
Tout est dans le titre, parfois en voiture, le menu ne s'ouvre pas.
Obliger de sortir, ouvrir, rentrer.

**Comment by Korioz** [comment]
Do you have a repro ?

**Comment by DVTGroup** [comment]
I have had this as well, as far as for my situation it’s fixed. I think the ELSFivem was the issue. We now use ELSPlus and it all works perfectly.

**Comment by Korioz** [comment]
fixed apparently not related to `krz_personalmenu`
