### ISSUE TITLE
Menu don't Open !

### ISSUE THREAD

**Issue by Rubylium** [Korioz/krz_personalmenu#3]
Salut ! J'ai bien NativUI d'installer, mais le menu ne se lance absolument pas, la seul erreur que j'ai pu trouver, c'est celle si : 
![image](https://user-images.githubusercontent.com/19718604/60611976-ee164380-9dc7-11e9-9a51-4ead2bec7d14.png)

Deuxième question, j'ai vue qu'il y avait un système audio intégré dans le menu si je me trompe pas, mais celui si est RP ? Il gère les distance etc ?

**Comment by ItsikNox** [comment]
C'est parce que tu dois utilisé une ancienne version de es_extended qui n'a pas la fonction Math

**Comment by Korioz** [comment]
Exact la plupart des gens n'ont pas le dossier common avec les fonctions requises je t'invite à le rajouter ou à réinstaller es_extended

**Comment by ItsikNox** [comment]
C'est surtout que la plupart des gens utilise la base de TaLife pour le double jobs et on donc pas cette fonction

**Comment by Rubyliss** [comment]
Très bien, pour se qui est de mettre à jours es_extended, je remplace juste les fichiers par ceux de la dernière version ou alors il y à pas mal de chose à changer etc ?

**Comment by ItsikNox** [comment]
Personnellement je te dirais de mettre a jour déjà pour une question de sécurité et de performance.

**Comment by Rubyliss** [comment]
J'ai mis à jours ESX, le menu marche sans problème à part les options de
données les items qui ne trouve pas le joueurs en fasse de moi, mais je
suis sur a 90% que c'est ma verison de ESX et tout les autres add-ons qui
sont du coup plus vraiment à jours.
Je vais regarder tout ça, en tout cas super menu !
( Je vient aussi de remarquer le mod fantôme, /invisible, quand on l'active
ça nous met invisible une fraction de seconde et ça s'enlève, pareille pour
l'invisibilité du NoClip, le NoClip marche mais on est visible)

**Comment by ItsikNox** [comment]
Les bugs viennent vraiment de ton coté car moi tout fonctionne niquel :)

**Comment by Rubyliss** [comment]
Vue que le serveur pour le quels je travail utilisais la vielle base TaLife
et que j'ai forcer la mise à jours ESX dessus, je suis pas vraiment étonné
tu vois x)
Je pense que la meilleurs des choses est de repartir de A-Z et de faire une
base toute propre avec le magnifique menu ;)

Merci de m'avoir aider en tout cas.

**Comment by ItsikNox** [comment]
Je pense que c'est une bonne solution ^^
