### ISSUE TITLE
Help Support for the new ESX

### ISSUE THREAD

**Issue by ManuDay** [Korioz/krz_personalmenu#30]
Since the new ESX update, the wallet for giving money and throwing it away no longer work and do not find the error either

**Comment by SamGordonSG** [comment]
Same problem here mate, I'm considering downgrading to an older version. I've tried everything I know of but nothing worked. If you foundd the solution to the problem I'd be glad to know

**Comment by ManuDay** [comment]
I'm constantly looking where but find nowhere a mistake which really surprises me because only the wallet does not work bank, and black money works

**Comment by ManuDay** [comment]
> Same problem here mate, I'm considering downgrading to an older version. I've tried everything I know of but nothing worked. If you foundd the solution to the problem I'd be glad to know

As well as I know where the error is, es_extended has now added account_money which did not previously exist, which you can find by the way under client at about 700 line where money bank and black_money there is money was not made with account_money so that's why these errors have tried to fix but somehow new bugs come in so I’ll look at it further

**Comment by SamGordonSG** [comment]
Been trying to fix that as well in es_extended it refers to money as an inventory item which by the way works great using the tradintional old fashion inventory thingy implemented directly into es_extended however, when trying to callback on the function in krz personalmenu, it somehow does not recognize money at all which is surprising. So I've added the function give and remove money directly into esx which does not seem to work. Then I've tryed to create the give and remove money function server side in krz which does not work either. It really is getting on my nerves, it is the last thing that stops me from opening my server to the public which make it kind of annoying

**Comment by SamGordonSG** [comment]
I see you made a pull request I had hope but then saw that you only changed the readme by adding "FIX FOR NEW ESX" dude emotional elevators like that... That's not cool man

**Comment by ManuDay** [comment]
I know but I want it to finally be changed because without making any file you can't make a pull request either, that's why

**Comment by ManuDay** [comment]
as said Korioz replied; Would work when i have time to adapt my script to the latest es_extended if you achieve to make it make a pull request

**Comment by AODeltaB** [comment]
Hello, I have just make a Pull Request, the wallet now works.

**Comment by ManuDay** [comment]
> Hello, I have just make a Pull Request, the wallet now works.


lulw I didn't think of that

**Comment by Korioz** [comment]
Fixed sorry but don't have time to fix before ! (even if it taken only 10 minutes xD)
