### ISSUE TITLE
NO OPEN MENU :(

### ISSUE THREAD

**Issue by saypapi** [Korioz/krz_personalmenu#31]
The menu does not open, but at the time of performing the actions with the ctrl, x, b keys. if they work
![Sin título](https://user-images.githubusercontent.com/51390169/78839836-49b0d580-79c7-11ea-9078-3fa554e1ed50.png)

**Comment by TipsyForFun** [comment]
Got the same issue, what do I do?

**Comment by Korioz** [comment]
Maybe fixed try now if not i know the cause and will investigate :)

**Comment by iamfr0st** [comment]
i have a similar error how to fixed it? thanks in advance

**Comment by DVTGroup** [comment]
You happen to have gcphone by any chance?
