### ISSUE TITLE
Beug de titre

### ISSUE THREAD

**Issue by GilBreysse** [Korioz/krz_personalmenu#34]
Je souhaiterais que lorsque je clique sur une catégorie de mon menu comme **"inventaire"** ça n'affiche pas le titre en haut comment le faire sauter ?
<img src="https://cdn.discordapp.com/attachments/701836842340974592/701837482643423252/54546446.png">

**Comment by GilBreysse** [comment]
**UP**

**Comment by Korioz** [comment]
On est pas sur un forum et ceci n'est pas un bug
