### ISSUE TITLE
Cant open Menu

### ISSUE THREAD

**Issue by 1UniQueGirl1** [Korioz/krz_personalmenu#38]
Hey, I can't open the menu in job cars like Ambulance and Police. How can I change this?

**Comment by DVTGroup** [comment]
Can’t open the menu at all.
ALT+E (for admin tp) works.
But the UI itself isn’t opening.
Checked everything possible, menu is a clean installed.

**Comment by Destructor** [comment]
Same problem

No error log...

`Creating script environments for krz_personalmenu
[97m======================================================================[0m
[97m[[94mAuthor[97m] [0m:[97m [97mKorioz[0m
[97m[[93mVersion[97m] [0m:[97m [97m2.0[0m
[97m[[32mDownload[97m] [0m:[97m [36mhttps://github.com/korioz/krz_personalmenu/releases[0m
[97m[[91mIssues[97m] [0m:[97m [36mhttps://github.com/korioz/krz_personalmenu/issues[0m
[97m======================================================================[0m
Started resource krz_personalmenu
Argument count mismatch (passed 2, wanted 3)`

**Comment by Korioz** [comment]
No info
