### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Venakiel** [Korioz/krz_personalmenu#4]
Salut, dis moi, pour les animations c'est possible de faire pour quel ne ce répète pas en continu ? Je m'explique, quand je fais un signe le signe ce répète non stop jusqu’à ce que je l'annule, dans le menu d'animation de base il fait un signe puis ce stop.

Merci de ton aide

**Comment by Korioz** [comment]
Possiblement dans une future maj

**Comment by Korioz** [comment]
Fixed
