### ISSUE TITLE
I cant join at my Server

### ISSUE THREAD

**Issue by thorbino2006** [Korioz/krz_personalmenu#40]
I add the Menu and join the Server, then i comming this

Couldn't load resource krz_personalmenu: Couldn't load resource krz_personalmenu from resources:/krz_personalmenu/: Could not open resource metadata file resources:/krz_personalmenu//__resource.lua.

i need the __resource.lua please

**Comment by elRazer** [comment]
Download the latest version (master).

**Comment by thorbino2006** [comment]
ok, can you give me the link pls? 
and how i can install it?
Thanks a lot for a fast answer.

**Comment by thorbino2006** [comment]
> Download the latest version (master).

where i can get it? and how did i use it?

**Comment by Korioz** [comment]
Server artifacts not updated (probably)
