### ISSUE TITLE
Console Error when use Personal Menu

### ISSUE THREAD

**Issue by HurtsAsHell** [Korioz/krz_personalmenu#42]
Hi, when i use Personal Menu ( so, i select a button ) i recive this error :

```
InvokeNative: execution failed: Argument at index 1 was null.
SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed.
```

How i could resolve it?

**Comment by Korioz** [comment]
A TriggerClientEvent who didn't received valid arguments need more info and a repro

**Comment by HurtsAsHell** [comment]
Okay, could i have your discord? I will open a private repo and i will send you the link.
I don't know what ClientEvent could be
