### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by SlySh0w55** [Korioz/krz_personalmenu#44]
As soon as I want to open the menu here is what the console tells me :

``SCRIPT ERROR: @krz_personalmenu/server/main.lua:59: attempt to get length of a nil value (local 'result')
> ref (@krz_personalmenu/server/main.lua:59)
>  (@mysql-async/mysql-async.js:14431)``

Tank

**Comment by Korioz** [comment]
you don't have esx billing sql file

**Comment by CesAlonso** [comment]
The same happens to me, but they are other mistakes:

SCRIPT ERROR: @esx_society/client/main.lua:57 attempt to index a nil value (global 'ESX')
SCRIPT ERROR: @krz_personalmenu/client/main.lua:292: attempt to index a nill value (global 'ESX')
SCRIPT ERROR: @odznaka/client.lua: 46 attempt to index a nil value (field 'job')
SCRIPT ERROR: @compass/compass. lua: 57 attempt to index a nil value (field 'job')

How can I fix it?
