### ISSUE TITLE
Money dont show up

### ISSUE THREAD

**Issue by Knabbermann** [Korioz/krz_personalmenu#45]
Hello,
the money on the player isnt showing in the menu. i only get bank money and black money.

i am not working with the newest version of esx, so the pull request doesnt helped me

**Comment by Knabbermann** [comment]
https://github.com/Korioz/krz_personalmenu/pull/43

with the updated client/main.lua and server/main.lua, it finally works.

**Comment by W4RdZ** [comment]
Do you speak about the main.lua of krz ?
