### ISSUE TITLE
How can i translate to english ?

### ISSUE THREAD

**Issue by xXMrPotatoXx** [Korioz/krz_personalmenu#48]
?

**Comment by DVTGroup** [comment]
Open the config.lua and search for Config.Locale 
This will default be set to “fr”, change this to “en” and restart the resource. Keep in mind that the locale needs to be loaded in the __resource.lua or fxmanifast.lua and be present in the resource. If you want to add one, place a .lua script in the locales folder and name it to the language you set. (For example ES). Then copy paste it from the en.lua locale. Change “en” to “es”, change it in the config.lua and add it to the __resource.lua or fxmanifast.lua
