### ISSUE TITLE
The Menu doesn't open [EN/FR]

### ISSUE THREAD

**Issue by mehdiachrafvbr** [Korioz/krz_personalmenu#55]
![error](https://user-images.githubusercontent.com/69818430/90435984-2e21ae00-e0d0-11ea-8a24-38eb5f70ffa6.PNG)
![erroor](https://user-images.githubusercontent.com/69818430/90436377-d172c300-e0d0-11ea-817b-1e64e1d46315.PNG)
This is the error message which appears When trying to open the menu with F5 key

**Comment by Korioz** [comment]
The only thing you see as a problem is the Menu?
Dude you have 5 errors about ESX that's not related to my Menu.
