### ISSUE TITLE
Some Problems ... (Money doesnt show // index nil)

### ISSUE THREAD

**Issue by Locopengu96** [Korioz/krz_personalmenu#58]
Hello,

your Menu works fine. but i get this Error : 

SCRIPT ERROR: @krz_personalemnu/client/main.lua:179: attempt to index a nil value (global 'ESX')

And the Money doesn't show. 
even after restarting the script.

**Comment by Locopengu96** [comment]
I fixed the Problem with my Error but my money still doesn't show up.

**Comment by JulienONN65** [comment]
On the client/main.lua in function RenderWalletMenu(), in the menu copy and past this code

`
		RageUI.List(_U('wallet_money_button', ESX.Math.GroupDigits(ESX.PlayerData.money)), PersonalMenu.WalletList, PersonalMenu.WalletIndex["money"] or 1, nil, {}, true, function(Hovered, Active, Selected, Index)
			if (Selected) then
				if Index == 1 then
					local post, quantity = CheckQuantity(KeyboardInput('KORIOZ_BOX_AMOUNT', _U('dialogbox_amount'), '', 8))
		
					if post then
						local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
		
						if closestDistance ~= -1 and closestDistance <= 3 then
							local closestPed = GetPlayerPed(closestPlayer)
		
							if not IsPedSittingInAnyVehicle(closestPed) then
								TriggerServerEvent('esx:giveInventoryItem', GetPlayerServerId(closestPlayer), 'item_money', "money", quantity)
								RageUI.CloseAll()
							else
								ESX.ShowNotification(_U('in_vehicle_give', 'de l\'argent'))
							end
						else
							ESX.ShowNotification(_U('players_nearby'))
						end
					else
						ESX.ShowNotification(_U('amount_invalid'))
					end
				elseif Index == 2 then
					local post, quantity = CheckQuantity(KeyboardInput('KORIOZ_BOX_AMOUNT', _U('dialogbox_amount'), '', 8))
		
					if post then
						if not IsPedSittingInAnyVehicle(plyPed) then
							TriggerServerEvent('esx:removeInventoryItem', 'item_money', "money", quantity)
							RageUI.CloseAll()
						else
							ESX.ShowNotification(_U('in_vehicle_drop', 'de l\'argent'))
						end
					else
						ESX.ShowNotification(_U('amount_invalid'))
					end
				end
			end
		
			PersonalMenu.WalletIndex["money"] = Index
		end)

`
