### ISSUE TITLE
possible bug¿?

### ISSUE THREAD

**Issue by SliderKP** [Korioz/krz_personalmenu#6]
when i try to give money to another player near for me, and the player is inside a car, the menu goes bug, and not can open again.

and i get this error in F8 console:
http://puu.sh/DRyXo/56dabbe302.jpg

In spite of some small mistakes, many thanks for making this menu, it is incredible and had a lot of acceptance

**Comment by Korioz** [comment]
Fixed in latest update thx for reporting !
