### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by peppinoita** [Korioz/krz_personalmenu#62]
Hi.
I have very high CPU usage for the menu, it goes from 0.70 to 1.0
![image](https://user-images.githubusercontent.com/12203647/98050121-57c9b600-1e31-11eb-9956-bc10792a248d.png)
Is it normal or do I made some mistakes on it?
Did you experience something similar?
Is there a way to reduce the cpu usage?

**Comment by MrWhitee4** [comment]
Yes I do have the same problem. Since the last FiveM update it has risen extremely when I open it. It needs a performance fix.

![image](https://user-images.githubusercontent.com/20826721/98149457-8f863b80-1ecd-11eb-94b7-67cb1007e0d8.png)

**Comment by Korioz** [comment]
i don't have these problems can you provide more info?

**Comment by MrWhitee4** [comment]
I fixed the issue with updating it. Now I'm at 3%.

**Comment by Korioz** [comment]
% don't mean anything -_-

**Comment by MrWhitee4** [comment]
> % don't mean anything -_-

Well I can tell you that because of the update it works now way much better so there has to be some kind of correlation. :)
