### ISSUE TITLE
Could not make hard link for ...

### ISSUE THREAD

**Issue by Mazda121** [Korioz/krz_personalmenu#65]
What's going on :(
The menu isn't opening

![image](https://user-images.githubusercontent.com/46310552/104829533-df28a200-5842-11eb-9412-809af5423728.png)

**Comment by ExeDesK** [comment]
Hey i have the same error i tried lowering the texture resolution in the ytd file but that doesn't fix the problem.
https://prnt.sc/xng95x

**Comment by Korioz** [comment]
You should not try to fix this as it's not even an error, hardlink have problems in linux it's related to the cfx-server code

**Comment by fatdesign** [comment]
> fix Just changer the folde name and start your server again. Solver your problem gays

Change the name to what? Can you be precise pls?
