### ISSUE TITLE
Goto / Bring

### ISSUE THREAD

**Issue by MarDevelopment** [Korioz/krz_personalmenu#67]
Hello an nice script :)

The menu is working just fine, an i love it,
but the goto / bring funktion dosent work. an no errors showing ?
What can i try ?

i looked true the code an can't see any ting wrong,
only meaby the the goto / bring is es_admin 2 an not es_extended ?

Sry for proberly bad english xD

**Comment by Korioz** [comment]
Use onesync we are in 2021

**Comment by MarDevelopment** [comment]
Øhhhh i am ? wow, but thanks for nothing
