### ISSUE TITLE
Finger Pointing doesnt work

### ISSUE THREAD

**Issue by Zazaa92** [Korioz/krz_personalmenu#69]
Hey i just Tried the Finger pointing  but it doesnt works 

Help me pls

**Comment by Korioz** [comment]
Info?
Repro?

It does works for me, i can't fix something that i don't experience without any info

**Comment by Atlass75** [comment]
Hi @Korioz 

The function to point fingers doesn't work with the latest FiveM build

**Comment by Hanashi** [comment]
`TaskMoveNetworkByName(plyPed, 'task_mp_pointing', 0.5, 0, 'anim@mp_point', 24)` seems to have no function in current version. It does nothing.

**Comment by Korioz** [comment]
Uhhh, yes it does?
