### ISSUE TITLE
Glasses Change to a different glasses, not remove

### ISSUE THREAD

**Issue by thefurrycanadian** [Korioz/krz_personalmenu#71]
When a female (have not tested as male) takes off their glasses, it exchanges them for a different pair of glasses, not take them off

**Comment by Korioz** [comment]
That's possible, gonna test and fix if that's the case

**Comment by thefurrycanadian** [comment]
I was able to add a few line of code to fix it, basically female no glasses is glasses 5, not 0

**Comment by thefurrycanadian** [comment]
added this at line 397 of client/main.lua

elseif _accessory == 'glasses' then
	if skin.sex == 0 then
		mAccessory = 0
	else
		mAccessory = 5
	end
