### ISSUE TITLE
How to change header

### ISSUE THREAD

**Issue by TheRealAsiate** [Korioz/krz_personalmenu#73]
How do I change the header from the menu into a picture? Like I remove the title and change the background like in this link: https://forum.cfx.re/t/help-anyone-know-what-this-menu-is-called/962403

**Comment by TrevorBarns** [comment]
### Banner: 
You stream 'commonmenu.ytd' which includes texture 'interaction_bgd'. This will however change header images for all scripts that utilize this banner (e.g. vMenu, etc.). 

More information here:
https://forum.cfx.re/t/how-to-add-a-custom-banner-to-vmenu-the-solution/1856028

### Title: 
Changing [this](https://github.com/Korioz/krz_personalmenu/blob/master/config.lua#L19) should change the title, to remove it try replacing with ' '.
