### ISSUE TITLE
Bug Argent

### ISSUE THREAD

**Issue by SilverLeBebeOurs** [Korioz/krz_personalmenu#76]
Bonjour,
J'ai un bug pour afficher l'argent sur le menu perso.
![image](https://user-images.githubusercontent.com/85455324/126398085-1081c33e-a77a-4673-b2a8-2588c56ddefb.png)

**Comment by DrDiablooz** [comment]
Salut, as-tu trouvé une solution à ce problème stp ? Merci

**Comment by Korioz** [comment]
Duplicata of #58
