### ISSUE TITLE
krz_Personalmenu won't open ... 

### ISSUE THREAD

**Issue by Max8569** [Korioz/krz_personalmenu#77]
Hi, 

When I'm trying to open krz_personalmenu it won't open and I'm trying so hard to solve the problem but I don't find the problem ... !

Here the Error: [script:krz_personalm] SCRIPT ERROR: @krz_personalmenu-2.0/server/main.lua:65: attempt to index a nil value (local 'xPlayer')

I need help Please THX

Picture: 

![](https://cdn.discordapp.com/attachments/792490552264359946/868585130443284550/unknown.png)

**Comment by Wiggie-Scripts** [comment]
And you're framework is ESX?

**Comment by Korioz** [comment]
Assuming you have the same error with `esx_billing` the issue is for sure not related to my resource. Please contact `es_extended` owners.
