### ISSUE TITLE
cant get some features to work

### ISSUE THREAD

**Issue by SlappZ** [Korioz/krz_personalmenu#81]
i keep getting a lock next to godmode , invinciblemode , grant money and grant money bank & dirty  how do i get them to work?

**Comment by lusorxdeko** [comment]
you have to scroll down in the config to the admin area there you can set which groups have access to the certain functions 
here's an example here you See 
_dev', 'owner', 'superadmin', 'admin', 'mod'
Can access this function so you Set the Group you want to get access to this function 


name = 'goto',		label = _U('admin_goto_button'),		groups = {'_dev', 'owner', 'superadmin', 'admin', 'mod'},		command = function()			local plyId = KeyboardInput('KORIOZ_BOX_ID', _U('dialogbox_playerid'), '', 8) 			if plyId ~= nil then				plyId = tonumber(plyId)								if type(plyId) == 'number' then					TriggerServerEvent('krz_personalmenu:Admin_BringS', GetPlayerServerId(PlayerId()), plyId)				end			end 			RageUI.CloseAll()		end

hope that helps you
