### ISSUE TITLE
Investors Full?

### ISSUE THREAD

**Issue by FritLP** [Korioz/krz_personalmenu#82]
When i want to farm, i received the message, that my Inventory is full. I changed in es_extended the weight to 500. Have i must to change someone in the personalmenu?

**Comment by lusorxdeko** [comment]
Nah dont think so it just shows your invetory but did you restart your server?

**Comment by FritLP** [comment]
Yes, I just created a completely new ESX Plume server only with the farm plugin, then I can farm once and then supposedly my inventory is full, although now I even made the maxweight in es_extended to 25000 :(

**Comment by lusorxdeko** [comment]
Then maybe check your database in the item tab on weight maybe there is your problem

**Comment by FritLP** [comment]
Everything is ok, the weight is set to 1. When I activate the standard es_extended inventory, it even says that I only have 1/25000. 👎

**Comment by FritLP** [comment]
I dont understand it..

**Comment by lusorxdeko** [comment]
Than its probably the farming Script itself i gues you can set what the Maximum is what you can pick up at once
