### ISSUE TITLE
Bring wont work

### ISSUE THREAD

**Issue by lusorxdeko** [Korioz/krz_personalmenu#83]
Hey i have the problem when i want to tp a Player to me i wont work if i Click on bring it tps me to the Player and if i click on go to it also tps me to the Player how do i fix it

**Comment by Korioz** [comment]
Are you using the latest `krz_personalmenu` version and OneSync Infinity ?

**Comment by TXIXMXRp** [comment]
yes

**Comment by lusorxdeko** [comment]
Ok nvm its fixen now i gues i works
