### ISSUE TITLE
Multiple enter key triggered

### ISSUE THREAD

**Issue by ITKewai** [Korioz/krz_personalmenu#85]
Hi, since yesterday we have a problem with the menu, once it is open when you press enter it counts it several times, as if it counts that it remains pressed for a few thousandths of a second; and in doing so you do not have time to select an option that maybe you go directly from "administration" to "teleport a player" without being able to choose other options such as giving money, noclip etc

you know how we can solve this?

![image](https://user-images.githubusercontent.com/44037081/144035389-a36aa6b1-e188-4234-914b-25c0d4313847.png)

**Comment by btwentyone** [comment]
Hello
Unfortunately from what I have seen, many of us have this concern. It happened suddenly for no reason.
Hope to find a solution

**Comment by ITKewai** [comment]
> Hello
> Unfortunately from what I have seen, many of us have this concern. It happened suddenly for no reason.
> Hope to find a solution

I've actually increase the citizen.wait for now...![Screenshot_2021-11-30-15-30-21-126_com.github.android.jpg](https://user-images.githubusercontent.com/44037081/144066516-8368d2ce-c792-45f5-bf8a-c01a4c55010e.jpg)

**Comment by btwentyone** [comment]
> > Hello
> > Unfortunately from what I have seen, many of us have this concern. It happened suddenly for no reason.
> > Hope to find a solution
> 
> I've actually increase the citizen.wait for now...![Screenshot_2021-11-30-15-30-21-126_com.github.android.jpg](https://user-images.githubusercontent.com/44037081/144066516-8368d2ce-c792-45f5-bf8a-c01a4c55010e.jpg)

I did the same to see, thanks for the info

**Comment by Korioz** [comment]
https://forum.cfx.re/t/menu-with-different-behavior-on-canary/4783825/3?u=korioz
Will fix this now.

**Comment by Korioz** [comment]
Fixed in d2320ff.
