### ISSUE TITLE
Cant switch between buttons

### ISSUE THREAD

**Issue by Duqino** [Korioz/krz_personalmenu#9]
[![Screenshot from Gyazo](https://gyazo.com/fcf641f7fafca987ee6535c829983c71/raw)](https://gyazo.com/fcf641f7fafca987ee6535c829983c71)

That happens when you press only ones on a key. (left or right does not matter)
Thats in the wallet menu. Somehow it switches between buttons so damn fast :S 

How can i fix this?

--edit--

oke the recording program cant even see it. Its like you hit the key 2 times in a millisecond.

**Comment by Korioz** [comment]
This is a Nativeui Lua Reloaded Problem its not of my business
