### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by JustHKN** [Korioz/krz_personalmenu#91]
Hey i have a problem i youse the newest version of the personalmenu and then i change someting in the config it will don´t work after it so i set the langue from fr to de and my Server Name after it the config had an error i done this like 10 times now i don´t have any ideas why its isn´t working
![Bild_2022-02-23_175815](https://user-images.githubusercontent.com/100305061/155368297-fbd9a96f-4eb5-47a9-a2cc-50c18557b58f.png)

**Comment by Korioz** [comment]
Not related to the resource you just badly edited the config file
