### ISSUE TITLE
bonjour gros pb je pete un plomb besoin de korioz svp

### ISSUE THREAD

**Issue by iphone59** [Korioz/krz_personalmenu#96]
les gars, je suis nouveau sur local host donc soyez cool, car c'est dur, 
qqun m'a aider à débuter, j'ai joué un peu,  
et y a 4jour un fichier se barre de php ou du fxserver, j'ai fai ce que j'ai pu pour comprendre le truc, mais impossible, j'y arriverai pas tt seul à rejouer comme avant sans aide, 
je m'explique,  j'avai ma petite ville trkl,  mon menu krz,
et pour que ca fonctionne nikel j'ai voulu remettre ce fichier dans mon php, mais en vain c'etait pire, 
j'ai aussi voulu mettre a jour l'artefact en pensant faire bien,  mais c'est pire sérieu,  le chat t ne va mm plu je sai pa pk,  mon menu krz ne va plus, ca fait 4jour je bosse a fond dessus je suis a bout,  si korioz pouvai me faire un support discord et arranger tt ca, 
je demande pa grand chose juste ma petite ville,  ce menu avec administration,  et qu'on me dise ou me montre comment mettre a jour svp,  car je trouve ca trop hard, je passe 7h sur un fichier et il ne fonctionne pa, 
merci d'avance
et php c'est pire,  sur les vidéo de aiden project et autres les sql passent, je fai comme eux mai les sql sont refusées,  j'y comprend vraiment rien,

**Comment by iphone59** [comment]
aidez moi svp,  j'aimerais bcp qu'on en parle sur discord,

**Comment by Korioz** [comment]
No information, impossible to understand, please detail with more info when you open an issue.

**Comment by iphone59** [comment]
t'es un bouffon tu troll t'es un guignol mon pote,  si tu comprend pa comment pa afficher un menu met toi une balle ca ira plu vite

**Comment by iphone59** [comment]
et on di salu qd on est poli connard,  tu te croi supérieur t'es une grosse merde
